/*
 * Pixel2CPP - Code Modal Component
 * 
 * MIT License
 * Copyright (c) 2025 CodeRandom
 * 
 * This software is provided free of charge for educational and personal use.
 * Commercial use and redistribution must comply with the MIT License terms.
 */

import React from "react";

/**
 * Code Modal component for displaying generated C++ code
 * 
 * @param {Object} props - Component props
 * @param {boolean} props.showCodeModal - Whether modal is visible
 * @param {Function} props.setShowCodeModal - Function to close modal
 * @param {Function} props.handleCopyCode - Function to copy code to clipboard
 * @param {string} props.copyStatus - Copy operation status
 * @param {Function} props.generateCppCode - Function to generate C++ code
 */
export default function CodeModal({ 
  showCodeModal, 
  setShowCodeModal, 
  handleCopyCode, 
  copyStatus, 
  generateCppCode 
}) {
  if (!showCodeModal) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-60 modal-backdrop flex items-center justify-center p-4 z-50" role="dialog" aria-modal="true" aria-labelledby="modal-title">
      <div className="bg-neutral-900 rounded-2xl p-6 max-w-5xl w-full max-h-[85vh] overflow-hidden flex flex-col shadow-2xl border border-neutral-700">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 id="modal-title" className="text-2xl font-bold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
              Generated C++ Code
            </h2>
            <p className="text-sm text-neutral-400 mt-1">
              Ready to use in your Arduino project
            </p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={handleCopyCode}
              className={`px-6 py-3 rounded-xl text-sm font-medium transition-all ${
                copyStatus === "copied" 
                  ? "bg-green-500 text-white shadow-lg" 
                  : copyStatus === "error"
                  ? "bg-red-500 text-white shadow-lg"
                  : "bg-blue-500 text-white hover:bg-blue-600 shadow-lg hover:shadow-xl"
              }`}
              aria-label="Copy generated code to clipboard"
            >
              {copyStatus === "copied" ? "✓ Copied!" : copyStatus === "error" ? "✗ Error!" : "📋 Copy Code"}
            </button>
            <button
              onClick={() => setShowCodeModal(false)}
              className="px-6 py-3 rounded-xl bg-neutral-800 hover:bg-neutral-700 text-sm transition-colors"
              aria-label="Close code modal"
            >
              ✕ Close
            </button>
          </div>
        </div>
        <div className="flex-1 overflow-auto">
          <pre className="bg-neutral-950 rounded-xl p-6 overflow-auto text-sm whitespace-pre-wrap border border-neutral-700 shadow-inner">
            {(() => {
              try {
                const code = generateCppCode();
                console.log('Generated code length:', code.length);
                return code || '// No code generated - please check console for errors';
              } catch (error) {
                console.error('Error generating code:', error);
                return `// Error generating code: ${error.message}\n// Please check console for details`;
              }
            })()}
          </pre>
        </div>
        <div className="mt-4 text-xs text-neutral-500 text-center">
          Generated by Pixel2CPP • Made by <a href="https://coderandom.com" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300">CodeRandom</a>
        </div>
      </div>
    </div>
  );
}
